# Generated by Django 4.2.6 on 2023-10-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('choice_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date submitted')),
            ],
        ),
    ]
