# Generated by Django 4.2.6 on 2023-11-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_pub_date_response_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(verbose_name='submition date'),
        ),
    ]
